### ISSUE TITLE
Any way to add some border-radius to the Calendly InlineWidget?

### ISSUE THREAD

**Issue by dominicwhyte** [tcampb/react-calendly#146]
Is there some way to add border radius to the Calendly InlineWidget to make it blend in with the page better? Not seeing any props that can be passed in for that.

Thanks!

**Comment by tcampb** [comment]
Hey @dominicwhyte, while there isn't currently a prop that allows you to change the iframe styles, you can use the following css selector to add a border-radius to the iframe:

```css
.calendly-inline-widget iframe,
.calendly-badge-widget iframe,
.calendly-overlay iframe {
    border-radius: 50px;
}
```
https://github.com/tcampb/react-calendly/blob/master/src/calendly-widget.css#L15
